#!/bin/bash

modules=(1 2) # 4 8 16 32 64 128) # Amount of modules
sizes=(1 2) # 4 8 16 32 64 128) # Image sizes
reps=${1:-50} # Default to 50 unless provided as argument

# LATENCY / THROUGHPUT EXPERIMENTS
echo "Running latency/throughput experiments"
echo "modules size latency(ms) throughput(MB/sec)" > "dipp_time_experiment.txt"
stdbuf -oL ./builddir/dipp -i ZMQ -p localhost -a 162 -q >> "dipp_time_experiment.txt" &
dipp_process=$!

for module in "${modules[@]}"; do
    echo "Executing with $module modules"
    for size in "${sizes[@]}"; do
        ./builddir/test_cam $size $reps $module
    done
done

sleep 10
kill $dipp_process >/dev/null 2>&1

# PERF EXPERIMENTS
echo "Running perf experiments"
echo "modules size rep cache-misses cache-references context-switches cpu-cycles instructions" > "dipp_perf_experiment.txt"
for module in "${modules[@]}"; do
    echo "Executing with $module modules"
    for size in "${sizes[@]}"; do
        for i in $(seq 1 $reps); do 
            ./builddir/test_cam $size 1 $module
            perf stat -e cache-misses,cache-references,context-switches,cpu-cycles,instructions ./builddir/dipp > "dipp_perf_result.txt" 2>&1

            perf_stats=($(grep -E 'cache-misses|cache-references|context-switches|cpu-cycles|instructions' "dipp_perf_result.txt" | awk '{gsub(",", ""); print $1}'))
            result="$module $size $i "

            for (( i = 0; i < 5; i++ )); do
                res=$((perf_stats[i]))
                result+=$(printf "%'d" "$res")" "
            done

            echo "${result% }" >> dipp_perf_experiment.txt  # Remove trailing space and print
        done
    done
done

rm "dipp_perf_result.txt"