#!/bin/sh
cd ../csh/builddir
./zmqproxy &
zmq=$!

sleep 2
cd ../../disco-radio-mimic
./builddir/radio &
radio=$!

sleep 2
cd ../DIPP
./builddir/test_cam &

sleep 2
./builddir/dipp | tee dipp_output.txt &
dipp=$!

# Wait for upload to complete
while ! grep -q "Uploaded" dipp_output.txt; do
    sleep 1
done

echo "Finished uploading"

sleep 10
kill $radio 
kill $dipp
kill $zmq 