#!/bin/bash

num_images=(1 2 4 2 1)

echo "Throughput for DIPP E2E with Demosaic and Encoding modules plus radio offload" > e2e_throughput.txt
echo "num_images execution_ms" >> e2e_throughput.txt
zmqproxy
zmq=$!
radio
radio=$!
for num_image in "${num_images[@]}"; do
    test_cam $num_image
    dipp
done
kill $zmq $radio
echo "Done"