/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: metadata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "metadata.pb-c.h"
void   metadata_item__init
                     (MetadataItem         *message)
{
  static const MetadataItem init_value = METADATA_ITEM__INIT;
  *message = init_value;
}
size_t metadata_item__get_packed_size
                     (const MetadataItem *message)
{
  assert(message->base.descriptor == &metadata_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t metadata_item__pack
                     (const MetadataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &metadata_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t metadata_item__pack_to_buffer
                     (const MetadataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &metadata_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MetadataItem *
       metadata_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MetadataItem *)
     protobuf_c_message_unpack (&metadata_item__descriptor,
                                allocator, len, data);
}
void   metadata_item__free_unpacked
                     (MetadataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &metadata_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   metadata__init
                     (Metadata         *message)
{
  static const Metadata init_value = METADATA__INIT;
  *message = init_value;
}
size_t metadata__get_packed_size
                     (const Metadata *message)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t metadata__pack
                     (const Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t metadata__pack_to_buffer
                     (const Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Metadata *
       metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Metadata *)
     protobuf_c_message_unpack (&metadata__descriptor,
                                allocator, len, data);
}
void   metadata__free_unpacked
                     (Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor metadata_item__field_descriptors[5] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MetadataItem, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(MetadataItem, value_case),
    offsetof(MetadataItem, bool_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MetadataItem, value_case),
    offsetof(MetadataItem, int_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(MetadataItem, value_case),
    offsetof(MetadataItem, float_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(MetadataItem, value_case),
    offsetof(MetadataItem, string_value),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned metadata_item__field_indices_by_name[] = {
  1,   /* field[1] = bool_value */
  3,   /* field[3] = float_value */
  2,   /* field[2] = int_value */
  0,   /* field[0] = key */
  4,   /* field[4] = string_value */
};
static const ProtobufCIntRange metadata_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor metadata_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MetadataItem",
  "MetadataItem",
  "MetadataItem",
  "",
  sizeof(MetadataItem),
  5,
  metadata_item__field_descriptors,
  metadata_item__field_indices_by_name,
  1,  metadata_item__number_ranges,
  (ProtobufCMessageInit) metadata_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor metadata__field_descriptors[8] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Metadata, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Metadata, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Metadata, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channels",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Metadata, channels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Metadata, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bits_pixel",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Metadata, bits_pixel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Metadata, camera),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Metadata, n_items),
    offsetof(Metadata, items),
    &metadata_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned metadata__field_indices_by_name[] = {
  5,   /* field[5] = bits_pixel */
  6,   /* field[6] = camera */
  3,   /* field[3] = channels */
  1,   /* field[1] = height */
  7,   /* field[7] = items */
  0,   /* field[0] = size */
  4,   /* field[4] = timestamp */
  2,   /* field[2] = width */
};
static const ProtobufCIntRange metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Metadata",
  "Metadata",
  "Metadata",
  "",
  sizeof(Metadata),
  8,
  metadata__field_descriptors,
  metadata__field_indices_by_name,
  1,  metadata__number_ranges,
  (ProtobufCMessageInit) metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
