#ifndef DIPP_PARAMIDS_H
#define DIPP_PARAMIDS_H

#define PARAMID_PIPELINE_RUN 1

/* Error log parameters */
#define PARAMID_ERROR_LOG 2

/* CSP Node IDs */
#define PARAMID_RADIO_NODE_ID 3

/* Module timeout parameter */
#define PARAMID_MODULE_TIMEOUT 4

/* Pipeline ids starting at 10 */
#define PARAMID_PIPELINE_CONFIG_1 10
#define PARAMID_PIPELINE_CONFIG_2 11
#define PARAMID_PIPELINE_CONFIG_3 12
#define PARAMID_PIPELINE_CONFIG_4 13
#define PARAMID_PIPELINE_CONFIG_5 14
#define PARAMID_PIPELINE_CONFIG_6 15

/* Module ids starting at 30 */
#define PARAMID_MODULE_PARAM_1 30
#define PARAMID_MODULE_PARAM_2 31
#define PARAMID_MODULE_PARAM_3 32
#define PARAMID_MODULE_PARAM_4 33
#define PARAMID_MODULE_PARAM_5 34
#define PARAMID_MODULE_PARAM_6 35
#define PARAMID_MODULE_PARAM_7 36
#define PARAMID_MODULE_PARAM_8 37
#define PARAMID_MODULE_PARAM_9 38
#define PARAMID_MODULE_PARAM_10 39
#define PARAMID_MODULE_PARAM_11 40
#define PARAMID_MODULE_PARAM_12 41
#define PARAMID_MODULE_PARAM_13 42
#define PARAMID_MODULE_PARAM_14 43
#define PARAMID_MODULE_PARAM_15 44
#define PARAMID_MODULE_PARAM_16 45
#define PARAMID_MODULE_PARAM_17 46
#define PARAMID_MODULE_PARAM_18 47
#define PARAMID_MODULE_PARAM_19 48
#define PARAMID_MODULE_PARAM_20 49

#endif