#include <param/param.h>
#include <stdio.h>
#include <string.h>
#include "param_config.h"
#include "vmem_config.h"

PARAM_DEFINE_STATIC_VMEM(PARAMID_ARB_PARAM_INT_0, arb_param_int_0, PARAM_TYPE_UINT16, -1 ,0, PM_DEBUG, NULL, NULL, config,VMEM_CONF_ARB_PARAM_INT_0_ADDR, NULL);
PARAM_DEFINE_STATIC_VMEM(PARAMID_ARB_PARAM_INT_1, arb_param_int_1, PARAM_TYPE_UINT16, -1 ,0, PM_DEBUG, NULL, NULL, config,VMEM_CONF_ARB_PARAM_INT_1_ADDR, NULL);
PARAM_DEFINE_STATIC_VMEM(PARAMID_ARB_PARAM_INT_2, arb_param_int_2, PARAM_TYPE_UINT16, -1 ,0, PM_DEBUG, NULL, NULL, config,VMEM_CONF_ARB_PARAM_INT_2_ADDR, NULL);
PARAM_DEFINE_STATIC_VMEM(PARAMID_ARB_PARAM_FLOAT_0, arb_param_float_0, PARAM_TYPE_FLOAT, -1 ,0, PM_DEBUG, NULL, NULL, config,VMEM_CONF_ARB_PARAM_FLOAT_0_ADDR, NULL);
PARAM_DEFINE_STATIC_VMEM(PARAMID_ARB_PARAM_FLOAT_1, arb_param_float_1, PARAM_TYPE_FLOAT, -1 ,0, PM_DEBUG, NULL, NULL, config,VMEM_CONF_ARB_PARAM_FLOAT_1_ADDR, NULL);
