#define PARAMID_PIPELINE_RUN 1
#define PARAMID_PIPELINE_CONFIG 2
#define PARAMID_MODULE_PARAM_1 3
#define PARAMID_MODULE_PARAM_2 4
#define PARAMID_MODULE_PARAM_3 5
#define PARAMID_MODULE_PARAM_4 6
#define PARAMID_MODULE_PARAM_5 7
#define PARAMID_MODULE_PARAM_6 8
